# GNU Makefile for LaTeX stuff using the latex-mk system.

NAME = asp_book
TEXSRCS =	acknowledgements.tex \
			bundle_adjustment.tex \
			correlation.tex \
			examples.tex \
			installation.tex \
			introduction.tex \
			outputfiles.tex \
			scripting.tex \
			stereo_testing_plan.tex \
			stereodefault.tex \
			tools.tex \
			tutorial.tex
# CLEAN_FILES+= $(wildcard *.aux)
USE_PDFLATEX = YES
VIEWPDF = open

include /opt/macports/share/latex-mk/latex.gmk
