# GNU Makefile for LaTeX stuff using the latex-mk system.

NAME = asp_book
TEXSRCS =	acknowledgements.tex \
			appendix.tex \
			bundle_adjustment.tex \
			getting_started.tex \
			installation.tex \
			introduction.tex \
			programs.tex
# CLEAN_FILES+= $(wildcard *.aux)
USE_PDFLATEX = YES
VIEWPDF = open

include /opt/macports/share/latex-mk/latex.gmk
