#!/usr/bin/env python
# __BEGIN_LICENSE__
#  Copyright (c) 2009-2026, United States Government as represented by the
#  Administrator of the National Aeronautics and Space Administration. All
#  rights reserved.
#
#  The NGT platform is licensed under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance with the
#  License. You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# __END_LICENSE__

"""
stereo_dist - Distributed stereo processing.
"""

import sys, argparse, subprocess, re, os, math, time, glob, shutil, platform
import os.path as P

# Set up the path to Python modules about to load
basepath    = os.path.abspath(sys.path[0])
pythonpath  = os.path.abspath(basepath + '/../Python')  # for dev ASP
libexecpath = os.path.abspath(basepath + '/../libexec') # for packaged ASP
sys.path.insert(0, basepath) # prepend to Python path
sys.path.insert(0, pythonpath)
sys.path.insert(0, libexecpath)

import asp_system_utils, asp_string_utils, asp_cmd_utils
asp_system_utils.verify_python_version_is_supported()
from asp_stereo_utils import * # must be after the path is altered above

# Prepend to system PATH
os.environ["PATH"] = libexecpath + os.pathsep + os.environ["PATH"]

# Ensure we can look up the ASP libraries
if 'ASP_LIBRARY_PATH' in os.environ:
    os.environ['LD_LIBRARY_PATH'] = os.environ['ASP_LIBRARY_PATH']

def run_stereo_prog(prog, opt, args, extra_args=[]):
    '''Run a stereo program with the given arguments.'''
    binpath = asp_system_utils.bin_path(prog)
    call = [binpath]
    call.extend(args)
    call.extend(extra_args)
    #if opt.dryrun or opt.verbose:
    print(' '.join(call))
    if not opt.dryrun:
        status = subprocess.call(call)
        if status != 0:
            asp_system_utils.raise_error(prog + ' failed')

if __name__ == '__main__':
    usage = '''stereo_dist [options] <images> [<cameras>]
                  <output_file_prefix> [DEM]
        Distributed stereo processing.\n''' + asp_system_utils.get_asp_version()

    p = argparse.ArgumentParser(usage=usage)
    p.add_argument('-v', '--version', dest='version', default=False, action='store_true',
                   help='Display the version of software.')
    p.add_argument('--verbose', dest='verbose', default=False, action='store_true',
                   help='Display the commands being executed.')
    p.add_argument('--dry-run', dest='dryrun', default=False, action='store_true',
                   help='Do not launch the jobs, only print the commands that should be run.')
    p.add_argument('--tile-size', dest='tile_size', default=1024, type=int,
                   help='Size of each tile for distributed processing.')
    p.add_argument('--tile-padding', dest='tile_padding', default=256, type=int,
                   help='Padding around each tile to avoid boundary artifacts.')

    (opt, args) = p.parse_known_args()
    args = asp_cmd_utils.clean_args(args)

    if opt.version:
        asp_system_utils.print_version_and_exit()

    if not args and not opt.version:
        p.print_help()
        asp_system_utils.raise_error('\nERROR: Missing input files', code=2)

    # Run stereo_pprc with --stop-after-stats to compute statistics only
    run_stereo_prog('stereo_pprc', opt, args, ['--stop-after-stats'])

    # Run stereo_parse to generate the tile list
    tile_params = ['--stereo-dist-tile-params', str(opt.tile_size), str(opt.tile_padding)]
    run_stereo_prog('stereo_parse', opt, args, tile_params)

    sys.exit(0)
