#!/usr/bin/env python
# __BEGIN_LICENSE__
#  Copyright (c) 2009-2026, United States Government as represented by the
#  Administrator of the National Aeronautics and Space Administration. All
#  rights reserved.
#
#  The NGT platform is licensed under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance with the
#  License. You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# __END_LICENSE__

"""
stereo_tile - Process a single tile for distributed stereo.
"""

import sys, argparse, subprocess, re, os, math, time, glob, shutil, platform
import os.path as P

# Set up the path to Python modules about to load
basepath    = os.path.abspath(sys.path[0])
pythonpath  = os.path.abspath(basepath + '/../Python')  # for dev ASP
libexecpath = os.path.abspath(basepath + '/../libexec') # for packaged ASP
sys.path.insert(0, basepath) # prepend to Python path
sys.path.insert(0, pythonpath)
sys.path.insert(0, libexecpath)
# Import after setting up the paths
import asp_system_utils, asp_string_utils, asp_cmd_utils, asp_stereo_utils, asp_alg_utils
asp_system_utils.verify_python_version_is_supported()

# Prepend to system PATH
os.environ["PATH"] = libexecpath + os.pathsep + os.environ["PATH"]

# Ensure we can look up the ASP libraries
if 'ASP_LIBRARY_PATH' in os.environ:
    os.environ['LD_LIBRARY_PATH'] = os.environ['ASP_LIBRARY_PATH']

def symlinkStatsFiles(outPrefix, tileSubdir, tilePrefix):
    '''Symlink stats files from parent directory to tile subdir.'''
    for f in glob.glob(outPrefix + '*stats.tif'):
        if os.path.isdir(f):
            continue
        relSrc = os.path.relpath(f, tileSubdir)
        dstF = f.replace(outPrefix, tilePrefix)
        if not os.path.lexists(dstF):
            os.symlink(relSrc, dstF)

def getTileByIndex(outPrefix, tileIndex):
    '''Read the tile list and return (BBox, padding) for the given tile index.'''
    tiles = asp_stereo_utils.readDistTileList(outPrefix)

    if tileIndex < 0 or tileIndex >= len(tiles):
        asp_system_utils.raise_error('Tile index ' + str(tileIndex) +
                                     ' out of range [0, ' + str(len(tiles) - 1) + ']')

    return tiles[tileIndex]

if __name__ == '__main__':
    usage = '''stereo_tile [options] <images> [<cameras>]
                  <output_file_prefix> [DEM]
        Process a single tile for distributed stereo.\n''' + asp_system_utils.get_asp_version()

    p = argparse.ArgumentParser(usage=usage)
    p.add_argument('-v', '--version', dest='version', default=False, action='store_true',
                   help='Display the version of software.')
    p.add_argument('--verbose', dest='verbose', default=False, action='store_true',
                   help='Display the commands being executed.')
    p.add_argument('--dry-run', dest='dryrun', default=False, action='store_true',
                   help='Do not launch the jobs, only print the commands that should be run.')
    p.add_argument('--tile-index', dest='tile_index', default=None, type=int,
                   help='Index of the tile to process (0-based).')
    p.add_argument('-e', '--entry-point', dest='entry_point', default=0, type=int,
                   help='Stereo pipeline entry point (0=pprc, 1=corr, 2=blend, 3=rfne, '
                   '4=fltr, 5=tri, 6=cleanup).')
    p.add_argument('--stop-point', dest='stop_point', default=7, type=int,
                   help='Stereo pipeline stop point (stop before this step).')

    (opt, args) = p.parse_known_args()
    args = asp_cmd_utils.clean_args(args)

    if opt.version:
        asp_system_utils.print_version_and_exit()

    if not args and not opt.version:
        p.print_help()
        asp_system_utils.raise_error('\nERROR: Missing input files', code=2)

    if opt.tile_index is None:
        asp_system_utils.raise_error('\nERROR: --tile-index is required', code=2)

    # Run stereo_parse to get settings
    sep = ","
    settings = asp_system_utils.run_and_parse_output("stereo_parse", args, sep,
                                                      opt.verbose)
    outPrefix = settings['out_prefix'][0]

    print("Output prefix: " + outPrefix)
    print("Tile index: " + str(opt.tile_index))

    (tile, padding) = getTileByIndex(outPrefix, opt.tile_index)
    print("Tile: " + tile.name_str() + ", padding: " + str(padding))

    # Create tile subdir
    tileSubdir = outPrefix + '-' + tile.name_str()
    asp_system_utils.mkdir_p(tileSubdir)
    tilePrefix = tileSubdir + '/' + os.path.basename(outPrefix)

    # Symlink stats files to the subdir
    symlinkStatsFiles(outPrefix, tileSubdir, tilePrefix)

    # Common extra args for all steps. For now only --corr-seed-mode 0 is supported,
    # so D_sub is avoided.
    # TODO(oalexan1): Enable using --corr-seed-mode 2 and 3. Maybe that will require
    # seeding directly D.tif.
    extraArgs = ['--output-prefix-override', tilePrefix,
                  '--stereo-dist-mode',
                  '--skip-low-res-disparity-comp',
                  '--corr-seed-mode', '0',
                  '--left-image-crop-win',
                  str(tile.x), str(tile.y), str(tile.width), str(tile.height),
                  '--sgm-collar-size', str(padding)]

    Step = asp_stereo_utils.Step

    if opt.entry_point <= Step.pprc < opt.stop_point:
        asp_stereo_utils.stereo_run('stereo_pprc', args, opt, extra_args=extraArgs)

    if opt.entry_point <= Step.corr < opt.stop_point:
        asp_stereo_utils.stereo_run('stereo_corr', args, opt, extra_args=extraArgs)

    # Skip blend - in distributed stereo each tile goes to point cloud/DEM independently,
    # then only final DEMs are merged. No cross-talk needed until DEM merging.

    if opt.entry_point <= Step.rfne < opt.stop_point:
        asp_stereo_utils.stereo_run('stereo_rfne', args, opt, extra_args=extraArgs)

    if opt.entry_point <= Step.fltr < opt.stop_point:
        asp_stereo_utils.stereo_run('stereo_fltr', args, opt, extra_args=extraArgs)

    if opt.entry_point <= Step.tri < opt.stop_point:
        asp_stereo_utils.stereo_run('stereo_tri', args, opt, extra_args=extraArgs)

    sys.exit(0)
