#include "DEM.h"

#include <stdlib.h>

void write_GMT_script(std::string const prefix,
                      int width, int height, double min_value, double max_value,
                      double scale_factor,
                      vw::cartography::GeoReference const& georef) {
  std::string filename = prefix + "-gmt.sh";
  std::string dem_filename = prefix + "-DEM.dem";
  std::string drg_filename = prefix + "-DRG.dem";

  std::cout << "\tWriting GMT script: " << filename << "\n";

  double left = georef.transform()(0,2);
  double top = georef.transform()(1,2);
  double right = georef.transform()(0,2) + (width-1) * georef.transform()(0,0);
  double bottom = georef.transform()(1,2) + (height-1) * georef.transform()(1,1);

  FILE *f = fopen(filename.c_str(), "w");

  fprintf(f, "# Generic Mapping Tools Contour Mapping Script\n");
  fprintf(f, "# \n");
  fprintf(f, "# Automatically generated by the Ames Stereo Pipeline\n");
  fprintf(f, "# You must have the GMT packages installed and in your search path.\n");
  fprintf(f, "# \n");
  fprintf(f, "xyz2grd %s -Gtemporary-dem.grd -Dlat/lon/alt/=/=/=/= -R%f/%f/%f/%f -I%e/%e -V -Zf \n", 
          dem_filename.c_str(),
          left, right, bottom, top,
          georef.transform()(0,0),
          -georef.transform()(1,1));
  fprintf(f, "xyz2grd %s -Gtemporary-drg.grd -Dlat/lon/alt/=/=/=/= -R%f/%f/%f/%f -I%e/%e -V -Zf \n", 
          drg_filename.c_str(),
          left, right, bottom, top,
          georef.transform()(0,0),
          -georef.transform()(1,1));
  fprintf(f, "grdinfo temporary-dem.grd \n");
  fprintf(f, "grdinfo temporary-drg.grd \n\n");


  std::string colorized_contour_name = prefix + "-DEM-colorized.ps";
  std::string texture_contour_name = prefix + "-DEM-contour.ps";
  fprintf(f, "export DEM_FILENAME=%s\n", colorized_contour_name.c_str());
  fprintf(f, "export DRG_FILENAME=%s\n", texture_contour_name.c_str());
  fprintf(f, "rm -f $DEM_FILENAME\n");
  fprintf(f, "rm -f $DRG_FILENAME\n");
  fprintf(f, "gmtset GRID_CROSS_SIZE 0 ANNOT_FONT_SIZE_PRIMARY 10\n\n");

  // DEM
  fprintf(f, "psbasemap -R%f/%f/%f/%f -Jx%fi -X1.5i -Y1.5i -B0 -P -K > $DEM_FILENAME\n",left, right, bottom, top, scale_factor);
  double color_scale = (max_value - min_value)/255.0;
  fprintf(f, "makecpt -Chaxby -T%f/%f/%f > g.cpt \n", min_value, max_value, color_scale);
  fprintf(f, "grdimage temporary-dem.grd -R%f/%f/%f/%f -Jx%fi -P -U/-0i/-0.25i/\"NASA Ames / MSSS\" -B10 -Cg.cpt -K > $DEM_FILENAME\n",left,right,bottom,top, scale_factor);
  int contour_interval = int(round((max_value - min_value) / 100))*10;
  if (contour_interval < 10) { contour_interval = 10; }
  fprintf(f, "grdcontour -R%f/%f/%f/%f temporary-dem.grd -Jx%fi -C%d -A50+s7 -Gd4i -Wc0.25p,- -Wa0.25p -O -K -T0.1i/0.02i >> $DEM_FILENAME\n\n", left,right,bottom,top,scale_factor,contour_interval);

  // DRG
  fprintf(f, "psbasemap -R%f/%f/%f/%f -Jx%fi -X1.5i -Y1.5i -B0 -P -K > $DRG_FILENAME\n",left, right, bottom, top, scale_factor);
  fprintf(f, "makecpt -Cgray -T0.0/1.0/%f > g.cpt\n", 1.0/255.0);
  fprintf(f, "grdimage temporary-drg.grd -R%f/%f/%f/%f -Jx%fi -P -U/-0i/-0.25i/\"NASA Ames / MSSS\" -B10 -Cg.cpt -K > $DRG_FILENAME\n",left,right,bottom,top,scale_factor);
  fprintf(f, "grdcontour -R%f/%f/%f/%f temporary-dem.grd -Jx%fi -C%d -A50+s7 -Gd4i -Wc0.25p,- -Wa0.25p -O -K -T0.1i/0.02i >> $DRG_FILENAME\n", left,right,bottom,top,scale_factor,contour_interval);

  fprintf(f, "rm -f .gmtcommands4 .gmtdefaults4 g.cpt\n");

  fclose(f);

}

