name: probe_isis_link
on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v3
    - name: probe_isis_link
      run: |
        chmod +x ./.github/workflows/probe_isis_link.sh
        ./.github/workflows/probe_isis_link.sh
